### ISSUE TITLE
Questions about SegmentedCustomControl

### ISSUE THREAD

**Issue by mtanml** [LanceMcCarthy/CustomXamarinDemos#20]
Hi Lance,

This is Marc... you recommended I try your SegmentedCustomControl in response to a support ticket.   It looks great -- I just have a few questions:

1.   When the control first appears, it looks perfect:

![image](https://user-images.githubusercontent.com/43346119/83774120-f10a5b80-a64a-11ea-84f0-4740cd8c5848.png)

But after I click different buttons a few times, the borders between the buttons start to disappear:

![image](https://user-images.githubusercontent.com/43346119/83774234-0e3f2a00-a64b-11ea-81ef-913e26880ffa.png)

2.   Are you able to provide a sample for detecting a change to SelectedIndex (the equivalent of SelectionChanged for the out-of-the-box Segmented Control)?

Thank you!

**Comment by LanceMcCarthy** [comment]
Hi Marc,

I can answer question 2 quickly. [the SelectionChanged event](https://docs.telerik.com/devtools/xamarin/controls/segmentedcontrol/selection#selection-changed) is the same as SelectedIndexChanged because it passes the index in the event args.

```csharp
private void RadSegmentedControl_OnSelectionChanged(object sender, ValueChangedEventArgs<int> e)
{
    var itemIndex = e.NewValue;
}
```

To answer question 1, that looks like it is getting squeezed to the left, which is causing the buttons to overlap. Look at the total width, then look at how each button got pushed to the left a little. 

![image](https://user-images.githubusercontent.com/3520532/83778492-c9ba8b00-a658-11ea-9dd8-e022e47b5eaa.png)

When it's squeezed like that, the borders are still there but is getting overlapped.

To fix this, you will need to examine the parent controls/layout that you have it in and make sure there are no constrained layouts.

For example, give the custom control an explicit WidthRequest or set the HorizontalOptions to Fill and make sure the parent doesn't put pressure on it to cause it to get pushed to the left

**Comment by mtanml** [comment]
Thanks for your quick reply!

I don't think the control shifted.   I think you're just seeing the inconsistency in my screen grabs.   This time I was more careful to grab the same area:

![image](https://user-images.githubusercontent.com/43346119/83794311-739f1500-a663-11ea-80e3-2c8c759cfab1.png)
 
Changes to:

![image](https://user-images.githubusercontent.com/43346119/83794435-a0532c80-a663-11ea-92d9-9cb42c6988ae.png)

I'm not having the disappearing border issue in iOS...   But in both platforms I'm trying to figure out why the control sometimes appears like this:

![image](https://user-images.githubusercontent.com/43346119/83790922-8c58fc00-a65e-11ea-8858-573cdc9f62bb.png)

Also, is it possible to remove the rounded corners on the individual buttons?   You can see them here on the selected button (this is iOS... I'm not seeing the same in Android):

![image](https://user-images.githubusercontent.com/43346119/83790981-a561ad00-a65e-11ea-942d-eed8d4d2e068.png)

**Comment by mtanml** [comment]
Also, sorry, I still can't figure out how to set this as the event handler for the control:

private void RadSegmentedControl_OnSelectionChanged(object sender, ValueChangedEventArgs<int> e)
{
    var itemIndex = e.NewValue;
}

**Comment by LanceMcCarthy** [comment]
oh, my apologies, you were talking about this control. No, there isn't any index changed event handlers or anything like this. It's just an early proof of concept to get you started with your own custom control.

You can add your own event handler and fire it when the SelectedIndex property is updated. Or you can take the easy route of using the Xamarin.Forms property changed event.

```xml
<ButtonSegments PropertyChanged="MyControl_PropertyChanged"/>
```

```csharp
public void MyControl_PropertyChanged(sender s, forgotThisArgsName e)
{
   if(e.PropertyName == nameof(ButtonSegments.SelectedIndex))
    {
        var index = (sender as ButtonSegments).SelectedIndex;
    }
}
```

Note: I'm typing all that from memory, you may need to slightly tweak it.


Regarding the squeezing, it looks like it is happening because all the button squeeze to the left, clipping the text. You may need to set each button's explicit HorizontalOptions to Fill to overcome this. Here's a link right to where the button is created. 
 https://github.com/LanceMcCarthy/CustomXamarinDemos/blob/f7aaf7e7996f6de6607cfa50ca94134f22abcf4a/SegmentedCustomControl/SegmentedCustomControl/Portable/Controls/ButtonSegments.xaml.cs#L139

while you're in there, you can also set the other things you want the button to have, liek setting the CornerRadius to 0 to remove that little radius.


At the end of the day, these are ultimate a set of `RadButtons` in an evenly spaced `Grid`. That link I pasted above shows you exactly where the buttons are created and you can make further customizations right there.

I will come back to this as soon as possible to take a closer look, but I need to do it in my spare time as I am working right now (I'm in east coast US). I think you will get most of the way there with the knowledge of how the segments are created :)

**Comment by mtanml** [comment]
Hey Lance, just wanted to let you know I figured out how to address all of the issues I had.   First, to handle a change to the ItemsSource, I added this to the CreateButtons method:

ButtonsGrid.ColumnDefinitions.Clear();

To handle the disappearing borders between the buttons, I set the background of ButtonsGrid to the same color as SelectedSegmentBackgroundColor, and changed ColumnSpacing to 1.

Thanks so much for this... working great for us!

**Comment by LanceMcCarthy** [comment]
Fantastic! I'm sorry I couldn't get to this in time, I'm happy to see you have a satisfactory end result.

So it looks like you have an understanding of how it works. Although it's not a complicated control, it can achieve pretty flexible results now that you know what's inside "the box" :)

I'll close this Issue, but please don't hesitate to post again if you have any other questions about how it works.
